# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YozgiAf4LecEQ_a5RtVvWRo6GPZjMxla
"""

pip install pycryptodome

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad
from Crypto.Random import get_random_bytes

def aes_encrypt(plaintext, key):
    cipher = AES.new(key, AES.MODE_ECB)
    ciphertext = cipher.encrypt(pad(plaintext, AES.block_size))
    return ciphertext

def aes_decrypt(ciphertext, key):
    cipher = AES.new(key, AES.MODE_ECB)
    plaintext = unpad(cipher.decrypt(ciphertext), AES.block_size)
    return plaintext

# Example usage
key = get_random_bytes(16)  # 16 bytes key for AES-128

plaintext = b'This is the plaintext message'
print("Plaintext:", plaintext)

ciphertext = aes_encrypt(plaintext, key)
print("Ciphertext:", ciphertext)

decrypted_plaintext = aes_decrypt(ciphertext, key)
print("Decrypted plaintext:", decrypted_plaintext)